import Head from "next/head";
import Image from "next/image";
import { TopNav } from "../components/TopNav";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main> Working out fine </main>

      <TopNav className/>
    </div>
  );
}
